Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -71,6 +71,21 @@ jobs:
           DOCKER_USER: ${{ secrets.DOCKER_USER }}
           DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
 
+      - name: Check if Release Already Exists for Requested Version
+        run: |
+          RELEASE_STATUS=$(
+            curl -L \
+              -H "Accept: application/vnd.github+json" \
+              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+              -H "X-GitHub-Api-Version: 2022-11-28" \
+              https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ env.AGBOT_VERSION }} \
+              | jq -r '.html_url')
+          
+          if [[ RELEASE_STATUS != 'null' ]]; then
+            echo "::error::Attempted to create a release for a version of Anax that already has a release page, see $RELEASE_STATUS"
+            exit 1
+          fi
+
   promote-images:
     needs: prepare-workflow
 
