Update release.yml

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -390,7 +390,20 @@ jobs:
           
           # Agent Files
           cd ./upload
-          gh run download -n anax-agent-files-v${AGBOT_VERSION}
+          if gh run download -n anax-agent-files-v${AGBOT_VERSION}; then
+            echo "::debug::Using artifact from build-push.yml run"
+          elif docker pull ${DOCKERHUB_REGISTRY}/anax_agent_files:${AGBOT_VERSION}; then
+            echo "::warning::Artifact not found in build-push.yml workflow, using docker image instead."
+            id=$(docker create --name temp_image_grab ${DOCKERHUB_REGISTRY}/anax_agent_files:${AGBOT_VERSION})
+            docker cp ${id}:agents .
+            cp ./agents/* .
+            rm -rf ./agents
+            docker container rm ${id}
+            docker image rm ${DOCKERHUB_REGISTRY}/anax_agent_files:${AGBOT_VERSION}
+          else
+            echo "::error::Artifact anax-agent-files-v${AGBOT_VERSION} not found in build-push.yml artifacts and Docker image ${DOCKERHUB_REGISTRY}/anax_agent_files:${AGBOT_VERSION} not found in Dockerhub"
+            exit 1
+          fi
 
       # Create GH release page
       # missing './release_files/upload/horizon-agent-macos-pkg-arm64.tar.gz'
